spring:
  application:
    name: DevWeaver


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
#    defer-datasource-initialization: true


  app:
    secret-key: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refreshtoken: ${JWT_REFRESH_TOKEN}

  stripe:
    api:
      secret: ${STRIPE_SECRET_KEY}
    webhook:
      secret: ${STRIPE_WEBHOOK_SECRET}


  client:
    url: http://localhost:8080

#  sql:
#    init:
#      mode: always     # run schema.sql + data.sql




