spring:
  application:
    name: DevWeaver


  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true


  app:
    secret-key: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    refreshtoken: ${JWT_REFRESH_TOKEN}


#  sql:
#    init:
#      mode: always     # run schema.sql + data.sql




